# Generated by Django 4.0.5 on 2022-07-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_childencategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='childencategory',
            name='slug',
            field=models.SlugField(default=1, verbose_name='Человекопонятный URL (само генерация)'),
            preserve_default=False,
        ),
    ]
