# Generated by Django 4.0.5 on 2022-07-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usercomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercomment',
            options={'verbose_name': 'Комментарий пользователю', 'verbose_name_plural': 'Комментарии пользователям'},
        ),
    ]
