# Generated by Django 4.0.5 on 2022-07-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usercomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='status_comment',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Не принята', 'Не принята'), ('Принята', 'Принята')], default='В ожидании', max_length=30, verbose_name='Статус комментария'),
        ),
    ]
