# Generated by Django 4.0.5 on 2022-06-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_setting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки'},
        ),
    ]
