# Generated by Django 4.0.5 on 2022-06-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_setting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='youtube',
            field=models.URLField(null=True),
        ),
    ]
