# Generated by Django 4.0.5 on 2022-06-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_setting_facebook_setting_instagram_setting_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
