# Generated by Django 4.0.5 on 2022-07-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_setting_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название сайта'),
        ),
    ]
