# Generated by Django 4.0.5 on 2022-07-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефонный номер')),
                ('problem', models.TextField(verbose_name='Проблема')),
                ('status', models.CharField(choices=[('В ожидании', 'В ожидании'), ('Решена', 'Решена'), ('Не решена', 'Не решена')], default='В ожидании', max_length=30, verbose_name='Статус обращения')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
