# Generated by Django 4.0.5 on 2022-07-04 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='second_post_image/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_post', to='posts.post')),
            ],
            options={
                'verbose_name': 'Дополнительные фотографии',
            },
        ),
    ]
