# Generated by Django 4.0.5 on 2022-07-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Дополнительная фотография', 'verbose_name_plural': 'Дополнительные фотографии'},
        ),
    ]
