# Generated by Django 4.0.5 on 2022-07-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Действительный пост'),
        ),
    ]
