# Generated by Django 4.0.5 on 2022-07-15 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0013_post_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_post', to='posts.post', verbose_name='Пост которому понравилось пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь которому понравилось пост')),
            ],
            options={
                'verbose_name': 'Понравилось пост',
                'verbose_name_plural': 'Понравились посты',
            },
        ),
    ]
